# Who are the artists credited with Work Y?
PREFIX sdo: <https://schema.org/>
SELECT ?person ?personName WHERE {
    BIND(<https://librarydata.hbs.edu/coins-and-conscience/3> AS ?workY)
    ?workY sdo:contributor ?person.
    ?person a sdo:Person ;
    	sdo:name ?personName .
}