# What is the topic of Work Y?
PREFIX sdo: <https://schema.org/>
SELECT ?topic ?topicName WHERE {
    BIND(<https://librarydata.hbs.edu/coins-and-conscience/3> AS ?workY)
    ?workY sdo:about ?topic .
    ?topic a sdo:DefinedTerm ;
    	sdo:name ?topicName .
}