# What topics has Artist X covered in their works?
PREFIX sdo: <https://schema.org/>
SELECT DISTINCT ?topic ?topicName WHERE {
    BIND(<http://www.wikidata.org/entity/Q1379395> AS ?artistX) .
    ?work a sdo:VisualArtwork ;
    	sdo:contributor ?artistX ;
    	sdo:about ?topic .
    ?topic a sdo:DefinedTerm ;
    	sdo:name ?topicName .
}