# What are all of the works credited to Artist X?
PREFIX sdo: <https://schema.org/>
SELECT ?work ?workId ?workName WHERE {
    BIND(<http://www.wikidata.org/entity/Q1379395> AS ?artistX) .
    ?work a sdo:VisualArtwork ;
    	sdo:name ?workName ;
    	sdo:identifier ?workId ;
    	sdo:contributor ?artistX .
}